### ISSUE TITLE
MISTy tutorial on spatial transcriptomics data

### ISSUE THREAD

**Issue by arutik** [saezlab/misty_pipelines#1]
Hi! I am willing to try MISTy on my spatial transcriptomics dataset and was wondering if there is any notebooks with tutorials?

Thanks

Best,
Anna Arutyunyan

**Comment by roramirezf** [comment]
Hi Anna,

We have added to the _st_pipeline_ folder a markdown with a tutorial. We are working on wrapper versions for 10x Visium data.

Cheers,
Ricardo
